import { index, jsonb, pgTable, text, timestamp } from 'drizzle-orm/pg-core'
import { user } from './auth-schema.js'
import type { LessonProgress, ScenarioProgress } from './merge.js'

// One row per learner: the payload is a few kB and merges field by field in merge.ts.
export const learner = pgTable('learner', {
  userId: text('user_id')
    .primaryKey()
    .references(() => user.id, { onDelete: 'cascade' }),
  lessons: jsonb('lessons').$type<Record<string, LessonProgress>>().notNull().default({}),
  scenarios: jsonb('scenarios').$type<Record<string, ScenarioProgress>>().notNull().default({}),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
})

// Separate from learner, so the row rewritten on every finished lesson stays small.
export const project = pgTable(
  'project',
  {
    // Generated by the client, so saving the same project twice updates one row.
    id: text('id').primaryKey(),
    userId: text('user_id')
      .notNull()
      .references(() => user.id, { onDelete: 'cascade' }),
    name: text('name').notNull(),
    source: text('source').notNull(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull(),
  },
  (table) => [index('project_user_id_idx').on(table.userId)],
)
